### ISSUE TITLE
规则管理对MatcherGroup不生效

### ISSUE THREAD

**Issue by zangxx66** [Lancercmd/nonebot_plugin_rauthman#3]
以```sv = MatcherGroup(type='message', rule=isInService('name'))```的方式定义rule，对```sv.on_command```等Matcher不生效，需要在```sv.on_command```定义rule才行，请问是nb2的Matcher不会继承MatcherGroup的属性还是我的用法有误

**Comment by Lancercmd** [comment]
@yanyongyu 目前确认了[当前版本](https://github.com/nonebot/nonebot2/releases/tag/v2.0.0a9)的 nonebot2 存在通过 MatcherGroup 定义 rule 的传递问题，请等待修复

**Comment by Lancercmd** [comment]
经测试，该问题已于 [v2.0.0a9.post1](https://github.com/nonebot/nonebot2/releases/tag/v2.0.0a9.post1) 被修复，本 Issue 将关闭
