### ISSUE TITLE
如何修改 `level` 的默认值

### ISSUE THREAD

**Issue by KomoriDev** [Lancercmd/nonebot_plugin_rauthman#34]

**Comment by Lancercmd** [comment]
https://github.com/Lancercmd/nonebot_plugin_rauthman/blob/master/nonebot_plugin_rauthman/RAM.py#L260-L261
```python
            elif not "level" in _groups[f"{group_id}"]:
                return 0
```
把 `0` 改为你需要的 `int` 值作为默认值

**Comment by KomoriDev** [comment]
# 请问如何使机器人默认开启所有功能呢
###  如果我想让机器人默认启用所有功能应怎么做？
